// BattleResultCard.js
import React from 'react';
import '../assets/css/battle-result-card.css';
import openaiLogo from '../assets/images/openai-logo.png';

const BattleResultCard = ({ winner, explanation }) => {
  return (
    <div className="result-card">
      <h2>🏆 Winner: {winner}</h2>
      <small>Generated by: </small><img src={openaiLogo} alt="Open AI Logo" style={{ width: 100 }} />
      <p>Explanation: {explanation}</p>
    </div>
  );
};

export default BattleResultCard;